package parser

import (
	"fmt"

	"github.com/mycok/monkey_interpreter/ast"
	"github.com/mycok/monkey_interpreter/lexer"
	"github.com/mycok/monkey_interpreter/token"
)

const (
	_           int = iota
	LOWEST          // Lowest rank after _
	EQUALS          // ==
	LESSGREATER     // > OR <
	SUM             // +
	PRODUCT         // *
	PREFIX          // -X OR !X
	CALL            // fn() OR myFunction(x)
)

type (
	prefixParseFn func() ast.Expression
	infixParseFn  func(ast.Expression) ast.Expression
)

// Parser represents a Parser object / type.
type Parser struct {
	l              *lexer.Lexer
	currToken      token.Token
	peekToken      token.Token
	errors         []string
	prefixParseFns map[token.TokenType]prefixParseFn
	infixParseFns  map[token.TokenType]infixParseFn
}

// New returns an initialized instance of a Parser.
func New(l *lexer.Lexer) *Parser {
	p := &Parser{
		l:      l,
		errors: []string{},
	}

	p.prefixParseFns = make(map[token.TokenType]prefixParseFn)
	p.registerPrefix(token.IDENT, p.parseIdentifier)

	// Read two tokens so that both currToken & peekToken are set.
	p.nextToken()
	p.nextToken()

	return p
}

func (p *Parser) registerPrefix(tokenType token.TokenType, fn prefixParseFn) {
	p.prefixParseFns[tokenType] = fn
}

func (p *Parser) registerInfix(tokenType token.TokenType, fn infixParseFn) {
	p.infixParseFns[tokenType] = fn
}

// Errors returns p.errors slice of string errors.
func (p *Parser) Errors() []string {
	return p.errors
}

func (p *Parser) peekError(t token.TokenType) {
	msg := fmt.Sprintf("expected next token to be %s, got %s instead", t, p.peekToken.Type)
	p.errors = append(p.errors, msg)
}

func (p *Parser) nextToken() {
	p.currToken = p.peekToken
	p.peekToken = p.l.NextToken()
}

// ParseProgram return an instance of *ast.Program as the root node with all the
// parsed statements as child nodes.
func (p *Parser) ParseProgram() *ast.Program {
	program := &ast.Program{}
	program.Statements = []ast.Statement{}

	for !p.curTokenIs(token.EOF) {
		stmt := p.parseStatement()
		if stmt != nil {
			program.Statements = append(program.Statements, stmt)
		}

		p.nextToken()
	}

	return program
}

func (p *Parser) parseStatement() ast.Statement {
	switch p.currToken.Type {
	case token.LET:
		return p.parseLetStatement()
	case token.RETURN:
		return p.parseReturnStatement()
	default:
		return p.parseExpressionStatement()
	}
}

func (p *Parser) parseExpression(precedence int) ast.Expression {
	fn := p.prefixParseFns[p.currToken.Type]
	if fn == nil {
		return nil
	}

	leftExp := fn()

	return leftExp
}

func (p *Parser) parseIdentifier() ast.Expression {
	return &ast.Identifier{Token: p.currToken, Value: p.currToken.Literal}
}

func (p *Parser) parseExpressionStatement() *ast.ExpressionStatement {
	stmt := &ast.ExpressionStatement{Token: p.currToken}
	stmt.Expression = p.parseExpression(LOWEST)

	if p.peekTokenIs(token.SEMICOLON) {
		p.nextToken()
	}

	return stmt
}

func (p *Parser) parseReturnStatement() *ast.ReturnStatement {
	// Create a Statement instance with the current p.currToken which in this case
	// should be a token of LET type.
	stmt := &ast.ReturnStatement{Token: p.currToken}
	p.nextToken()

	// TODO: Add expression parsing functionality.

	for !p.curTokenIs(token.SEMICOLON) {
		p.nextToken()
	}

	return stmt
}

func (p *Parser) parseLetStatement() *ast.LetStatement {
	// Create a Statement instance with the current p.currToken which in this case
	// should be a token of LET type.
	stmt := &ast.LetStatement{Token: p.currToken}

	if !p.peekExpectedType(token.IDENT) {
		return nil
	}

	// Create an Identifier instance with the current p.currToken which in this case
	// should be the IDENTIFIER token value after the LET token value. The current p.currToken
	// is generated by calling p.peekExpectedType helper which in turn calls p.nextToken().
	stmt.Name = &ast.Identifier{Token: p.currToken, Value: p.currToken.Literal}

	if !p.peekExpectedType(token.ASSIGN) {
		return nil
	}

	// TODO: Add expression parsing functionality.

	for !p.curTokenIs(token.SEMICOLON) {
		p.nextToken()
	}

	return stmt
}

func (p *Parser) curTokenIs(t token.TokenType) bool {
	return p.currToken.Type == t
}

func (p *Parser) peekTokenIs(t token.TokenType) bool {
	return p.peekToken.Type == t
}

func (p *Parser) peekExpectedType(t token.TokenType) bool {
	if p.peekTokenIs(t) {
		p.nextToken()

		return true
	}

	p.peekError(t)
	return false
}
